# Generated by Django 4.2.13 on 2025-11-17 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Code file name', max_length=200)),
                ('code', models.TextField(help_text='Code content')),
                ('language', models.CharField(choices=[('cpp', 'Arduino/C++'), ('c', 'C'), ('python', 'MicroPython')], default='cpp', help_text='Programming language', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Code description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ESP32 Code',
                'verbose_name_plural': 'ESP32 Codes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
